# Generated by Django 5.2.4 on 2025-08-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(related_name='members', through='companies.CompanyMember', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LANDLORD', 'Landlord'), ('TENANT', 'Tenant'), ('CORPORATE_TENANT', 'Corporate Tenant'), ('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=50),
        ),
    ]
