# Generated by Django 5.2.4 on 2025-08-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's phone number, including country code (e.g., +14155552671)", max_length=20, null=True, unique=True),
        ),
    ]
