databases:
  - name: chatsappdb
    plan: free
    databaseName: chatsappdb
    user: chatsappdb

services:
  - type: web
    plan: free
    name: app
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn app.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatsappdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
